language: node_js
node_js:
 - "8"

services:
 - docker

before_install:
 - docker pull ipfs/go-ipfs
 - docker run -d --name ipfs_host -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest
 - docker ps -a

script:
 - ganache-cli -p 7545 > /dev/null &
 - sleep 5
 - npm test
